### PR TITLE
Changed names for compatibility with newer relic version

### PR DESCRIPTION
**Pull request by furkanturan**
The new relic renames the `STS_ERR` to `RLC_ERR`, and the name of the curve file used for preset.

### CODE REVIEW

**Comment by lubux** [comment]
Looks good, but we also have to update `python-wrapper/pre_python.c` with the new relic names.

**Comment by furkanturan** [comment]
Hi,

I can change the `STS_*` to `RLC_*` easily, but I cannot test. In fact, the python part has never worked for me. It might be due to the library path settings in its compile configuration. I don't have sudo access to my work PC, so I compile everything from source code, and link them dynamically.

**Comment by lubux** [comment]
Hi,
Yes that would be great. You can check on travis if the build succeeds [travis](https://travis-ci.org/lubux/afgh-pre-relic). Currently, the build fails because of the `STS_*` labels in the `pre_python.c` file. Thanks for adapting the project to the new relic version :)

**Comment by furkanturan** [comment]
Travis succeeded now :)

**Comment by lubux** [comment]
Perfect 👍

**Pull request merged**
